# Generated by Django 2.2 on 2019-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='searcher',
            name='image',
            field=models.ImageField(default=1, upload_to='users/images', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
