# Generated by Django 2.2 on 2019-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_publisher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address_url',
            field=models.CharField(max_length=256, null=True, verbose_name='Address URL'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(null=True, upload_to='users/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='trading_doc',
            field=models.ImageField(null=True, upload_to='images/docs', verbose_name='Trading document'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website_url',
            field=models.CharField(max_length=256, null=True, verbose_name='Website URL'),
        ),
    ]
