# Generated by Django 2.2 on 2019-04-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190426_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searcher',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='searcher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Searcher'),
            preserve_default=False,
        ),
    ]
