# Generated by Django 2.2 on 2019-04-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190426_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searcher',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='users/images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='publisher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='users.Publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(100, 'Normal'), (101, 'Premuim')], default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='searcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to='users.Searcher'),
        ),
    ]
