# Generated by Django 2.2 on 2019-04-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190426_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='publisher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='users.Publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='searcher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to='users.Searcher'),
        ),
    ]
