# Generated by Django 2.2 on 2019-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190426_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='publisher',
            name='image',
            field=models.ImageField(default=1, upload_to='users/images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searcher',
            name='image',
            field=models.ImageField(default=1, upload_to='users/images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Publisher name'),
        ),
        migrations.AlterField(
            model_name='searcher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Searcher name'),
        ),
    ]
