# Generated by Django 2.2 on 2019-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190426_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='address_url',
            field=models.URLField(max_length=256, null=True, verbose_name='Address URL'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='facebook_url',
            field=models.URLField(max_length=256, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='instgram_url',
            field=models.URLField(max_length=256, null=True, verbose_name='Instgram URL'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='trading_doc',
            field=models.ImageField(default=1, upload_to='images/doc', verbose_name='Trading document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='twitter_url',
            field=models.URLField(max_length=256, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website_url',
            field=models.URLField(max_length=256, null=True, verbose_name='Website URL'),
        ),
    ]
