# Generated by Django 2.2 on 2019-04-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190426_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searcher',
            name='image',
        ),
    ]
