# Generated by Django 2.2 on 2019-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190426_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Day')),
            ],
        ),
        migrations.AlterField(
            model_name='publisher',
            name='work_end_at',
            field=models.TimeField(verbose_name='Work ends at'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='work_start_at',
            field=models.TimeField(verbose_name='Work starts at'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='holidays',
            field=models.ManyToManyField(to='users.Holiday', verbose_name='Holidays'),
        ),
    ]
