# Generated by Django 2.2 on 2019-05-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190509_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='users.Holiday', verbose_name='Holidays'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='trading_doc',
            field=models.ImageField(upload_to='images/docs', verbose_name='Trading document'),
        ),
    ]
