# Generated by Django 2.2 on 2019-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190510_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='holidays',
        ),
        migrations.AddField(
            model_name='publisher',
            name='holidays',
            field=models.CharField(blank=True, max_length=256, verbose_name='Holidays'),
        ),
    ]
