# Generated by Django 2.2 on 2019-07-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190510_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
