# Generated by Django 2.2 on 2019-07-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_subscription', to='offers.Discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_subscription', to='offers.Offer', verbose_name='Offer'),
        ),
    ]
