# Generated by Django 2.2 on 2019-07-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0027_auto_20190703_0036'),
        ('users', '0020_auto_20190703_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='SearcherNotification',
        ),
    ]
