# Generated by Django 2.2 on 2019-07-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0027_auto_20190703_0036'),
        ('users', '0021_auto_20190703_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchernotification',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_searcher_notifications', to='offers.Discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='searchernotification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_searcher_notifications', to='offers.Offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='searchernotification',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher_notifications', to='users.Searcher', verbose_name='Searcher'),
        ),
        migrations.CreateModel(
            name='AdvertiserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_notifications', to='users.Publisher', verbose_name='Advertiser')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_advertiser_notifications', to='offers.Discount', verbose_name='Discount')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_advertiser_notifications', to='offers.Offer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'AdvertiserNotification',
                'verbose_name_plural': 'AdvertiserNotifications',
            },
        ),
    ]
