# Generated by Django 2.2 on 2019-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190705_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisernotification',
            name='refuesed',
            field=models.BooleanField(default=False, verbose_name='Refused'),
        ),
    ]
