# Generated by Django 2.2 on 2019-07-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190705_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisernotification',
            options={'ordering': ['-id'], 'verbose_name': 'AdvertiserNotification', 'verbose_name_plural': 'AdvertiserNotifications'},
        ),
    ]
