# Generated by Django 2.2 on 2019-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190705_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
