# Generated by Django 2.2 on 2019-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190710_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
    ]
