# Generated by Django 2.2 on 2019-07-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0037_auto_20190720_2234'),
        ('users', '0028_auto_20190712_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisernotification',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_advertiser_notifications', to='offers.Story'),
        ),
    ]
