# Generated by Django 2.2 on 2019-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('small_image_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('small_image_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
        migrations.CreateModel(
            name='PlusItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('small_image_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
    ]
