# Generated by Django 2.2 on 2019-04-24 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('plus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plus_item_image', to='offers.PlusItem')),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_images', to='offers.Offer')),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
        migrations.CreateModel(
            name='DiscountImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/imags/', verbose_name='Image')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_image', to='offers.Discount')),
            ],
            options={
                'verbose_name': 'Offer image',
                'verbose_name_plural': 'Offer images',
            },
        ),
    ]
