# Generated by Django 2.2 on 2019-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='small_image_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plusitemimage',
            name='small_image_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
