# Generated by Django 2.2 on 2019-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20190425_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountimage',
            name='small_image_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
