# Generated by Django 2.2 on 2019-06-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_discountimage_small_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountimage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_images', to='offers.Discount'),
        ),
    ]
