# Generated by Django 2.2 on 2019-06-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20190510_1747'),
        ('offers', '0015_auto_20190525_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image', models.ImageField(upload_to='ads/images', verbose_name='Ad Image')),
                ('position', models.CharField(choices=[('Top', 'Top'), ('Buttom', 'Buttom')], max_length=256, verbose_name='Position')),
                ('period', models.PositiveSmallIntegerField(help_text='Please set ad period in seconds.', verbose_name='Period')),
                ('start_date', models.DateField(help_text='Start viewing date', verbose_name='Start date')),
                ('end_date', models.DateField(help_text='End viewing date', verbose_name='End date')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Publisher', verbose_name='Advertiser')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Discount', verbose_name='Discount')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Offer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
