# Generated by Django 2.2 on 2019-08-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190727_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='offer',
        ),
    ]
