# Generated by Django 2.2 on 2019-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20190811_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
