# Generated by Django 2.2 on 2019-07-26 22:56

import django.core.validators
from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Image')),
                ('small_image_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('precentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Precentage')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('visited', models.PositiveIntegerField(default=0, verbose_name='Visited')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Pending', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='FollowedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Followed category',
                'verbose_name_plural': 'Followed categories',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('visited', models.PositiveIntegerField(default=0, verbose_name='Visited')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Pending', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='OfferAndDiscountFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Feature name')),
                ('desc', models.TextField(max_length=1024, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Offer and discount feature',
                'verbose_name_plural': 'Offer and discount features',
            },
        ),
        migrations.CreateModel(
            name='PlusItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Plus item',
                'verbose_name_plural': 'Plus items',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(max_length=256, upload_to='stories/', validators=[helpers.validators.ImageOrVideo], verbose_name='Image/Video')),
                ('desc', models.TextField(max_length=1024, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Start date')),
                ('end_time', models.DateTimeField(verbose_name='Start date')),
                ('number_of_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Number of hours')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-id'],
            },
        ),
    ]
