# Generated by Django 2.2 on 2019-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='visited'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Visited'),
        ),
        migrations.AlterField(
            model_name='plusitem',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Description'),
        ),
    ]
