# Generated by Django 2.2 on 2019-07-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_stories', to='users.Publisher', verbose_name='Advertiser'),
        ),
        migrations.AddField(
            model_name='plusitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plus_offer', to='offers.Offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='offeranddiscountfeature',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_features', to='offers.Discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='offeranddiscountfeature',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_features', to='offers.Offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_offer', to='users.Publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='like',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_discount', to='offers.Discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='like',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_offer', to='offers.Offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='like',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='users.Searcher', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='followedcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_category_category', to='offers.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='followedcategory',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_category_user', to='users.Searcher', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offers.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_discount', to='users.Publisher', verbose_name='Publisher'),
        ),
        migrations.CreateModel(
            name='PendingDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Discount',
                'verbose_name_plural': 'Pending Discounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.discount',),
        ),
        migrations.CreateModel(
            name='PendingOffer',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Offer',
                'verbose_name_plural': 'Pending Offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.offer',),
        ),
        migrations.CreateModel(
            name='PendingStory',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Story',
                'verbose_name_plural': 'Pending Stories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.story',),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('searcher', 'offer', 'discount')},
        ),
        migrations.AlterUniqueTogether(
            name='followedcategory',
            unique_together={('searcher', 'category')},
        ),
    ]
