# Generated by Django 2.2 on 2019-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20190425_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='bending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='bending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plusitem',
            name='bending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plusitem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
