# Generated by Django 2.2 on 2019-08-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20190727_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='end_time',
        ),
    ]
