# Generated by Django 2.2 on 2019-08-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_story_end_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferAndDiscountFeature',
            new_name='OfferFeature',
        ),
    ]
