# Generated by Django 2.2 on 2019-04-25 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20190426_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plusitem',
            name='bending',
        ),
        migrations.RemoveField(
            model_name='plusitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plusitem',
            name='visible',
        ),
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='bending',
            field=models.BooleanField(default=True, verbose_name='Bending'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Visited'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='bending',
            field=models.BooleanField(default=True, verbose_name='Bending'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
