# Generated by Django 2.2 on 2019-04-26 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0004_auto_20190426_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BendingDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'Bending Discount',
                'verbose_name_plural': 'Bending Discounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.discount',),
        ),
        migrations.CreateModel(
            name='BendingOffer',
            fields=[
            ],
            options={
                'verbose_name': 'Bending Offer',
                'verbose_name_plural': 'Bending Offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.offer',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_discount', to='offers.Discount', verbose_name='Discount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_offer', to='offers.Offer', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Likes',
            },
        ),
    ]
