# Generated by Django 2.2 on 2019-08-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20190811_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerfeature',
            name='discount',
        ),
    ]
