# Generated by Django 2.2 on 2019-08-10 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_offerfeature_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 23, 25, 33, 452344, tzinfo=utc), verbose_name='End date'),
            preserve_default=False,
        ),
    ]
