# Generated by Django 2.2 on 2019-04-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_followedcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_category_user', to='users.Searcher', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='users.Searcher', verbose_name='User'),
        ),
    ]
