# Generated by Django 2.2 on 2019-08-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_story_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
    ]
