# Generated by Django 2.2 on 2019-04-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20190426_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_discount', to='users.Publisher', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_offer', to='users.Publisher', verbose_name='Publisher'),
        ),
    ]
