# Generated by Django 2.2 on 2019-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20190812_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='desc',
            field=models.TextField(max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
