# Generated by Django 2.2 on 2019-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_storyseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Caption'),
        ),
    ]
