# Generated by Django 2.2 on 2019-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190426_2040'),
        ('offers', '0009_auto_20190426_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
        migrations.AlterUniqueTogether(
            name='followedcategory',
            unique_together={('user', 'category')},
        ),
    ]
