# Generated by Django 2.2 on 2019-04-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190426_2040'),
        ('offers', '0011_remove_discount_visible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'offer', 'discount')},
        ),
    ]
