# Generated by Django 2.2 on 2019-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20190514_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
