# Generated by Django 2.2 on 2019-05-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_auto_20190525_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offers.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='offers.Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
