# Generated by Django 2.2 on 2019-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20190525_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='categories/images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
