# Generated by Django 2.2 on 2019-06-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_offeranddiscountfeature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeranddiscountfeature',
            unique_together={('offer', 'discount', 'name')},
        ),
    ]
