# Generated by Django 2.2 on 2019-06-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20190607_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeranddiscountfeature',
            unique_together=set(),
        ),
    ]
