# Generated by Django 2.2 on 2019-06-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_auto_20190607_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeranddiscountfeature',
            options={'verbose_name': 'Offer and discount feature', 'verbose_name_plural': 'Offer and discount features'},
        ),
    ]
