# Generated by Django 2.2 on 2019-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_auto_20190607_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='small_image_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
