# Generated by Django 2.2 on 2019-06-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190510_1747'),
        ('offers', '0023_auto_20190628_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='advertiser',
            new_name='searcher',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('searcher', 'offer', 'discount')},
        ),
    ]
