# Generated by Django 2.2 on 2019-07-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0025_auto_20190629_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='price',
        ),
    ]
