# Generated by Django 2.2 on 2019-07-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification'),
        ('offers', '0026_remove_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followedcategory',
            old_name='user',
            new_name='searcher',
        ),
        migrations.AlterUniqueTogether(
            name='followedcategory',
            unique_together={('searcher', 'category')},
        ),
    ]
