# Generated by Django 2.2 on 2019-07-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0028_offer_refuesed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='refuesed',
            new_name='refused',
        ),
    ]
