# Generated by Django 2.2 on 2019-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0029_auto_20190705_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='bending',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='bending',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='refused',
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('Bending', 'Bending'), ('Refused', 'Refused'), ('Published', 'Published')], default='Bending', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Bending', 'Bending'), ('Refused', 'Refused'), ('Published', 'Published')], default='Bending', max_length=50, verbose_name='Status'),
        ),
    ]
