# Generated by Django 2.2 on 2019-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_auto_20190705_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('Bending', 'Bending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Bending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Bending', 'Bending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Bending', max_length=50, verbose_name='Status'),
        ),
    ]
