# Generated by Django 2.2 on 2019-07-20 15:25

import django.core.validators
from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0031_auto_20190707_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(max_length=256, upload_to='stories/', validators=[helpers.validators.ImageOrVideo], verbose_name='Image/Video')),
                ('desc', models.TextField(max_length=1024, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Start date')),
                ('number_of_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Number of hours')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
