# Generated by Django 2.2 on 2019-07-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190712_1108'),
        ('offers', '0034_bendingstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='publisher',
        ),
        migrations.AddField(
            model_name='story',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Publisher', verbose_name='Advertiser'),
            preserve_default=False,
        ),
    ]
