# Generated by Django 2.2 on 2019-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0036_auto_20190720_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BendingDiscount',
        ),
        migrations.DeleteModel(
            name='BendingOffer',
        ),
        migrations.DeleteModel(
            name='BendingStory',
        ),
        migrations.CreateModel(
            name='PendingDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Discount',
                'verbose_name_plural': 'Pending Discounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.discount',),
        ),
        migrations.CreateModel(
            name='PendingOffer',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Offer',
                'verbose_name_plural': 'Pending Offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.offer',),
        ),
        migrations.CreateModel(
            name='PendingStory',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Story',
                'verbose_name_plural': 'Pending Stories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offers.story',),
        ),
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Published', 'Published')], default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
