# Generated by Django 2.2 on 2019-06-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20190510_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(100, 'Created'), (101, 'Canceled'), (102, 'Paid')], default=100, verbose_name='Status')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Publisher', verbose_name='Advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transactionattempt',),
        ),
    ]
