# Generated by Django 2.2 on 2019-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionattempt',
            name='payment_id',
            field=models.CharField(db_index=True, editable=False, max_length=256, null=True, verbose_name='Payment ID'),
        ),
    ]
